spring:
  profiles: dev
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/experiment?verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jackson:
    property-naming-strategy: SNAKE_CASE
  kafka:
    bootstrap-servers: 172.28.0.2:9092
  redis:
    host: 127.0.0.1

server:
  port: 8093

mybatis:
  configuration:
    cache-enabled: true
    map-underscore-to-camel-case: true

kafka-asr:
  bootstrap:
    address: 172.28.0.2:9092
  topic:
    userlog:
      name: speech_saas_user_log_live3

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: false