spring:
  profiles: dev
  application:
    name: database
  datasource:
    platform: mysql

    url: jdbc:mysql://localhost:3306/user?verifyServerCertificate=false&useSSL=false&requireSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always

server:
  port: 8081
